import { Footer } from "@/components/organisms/Footer";
import { Header } from "@/components/organisms/Header";
import { ProviderChakra } from "@/components/templates/ProviderChakra";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import { ProviderReactQuery } from "@/components/templates/ProviderReactQuery";
import { Providers } from "@/components/templates/Providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <main className="main_layout">
            <Header />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
