import { Footer } from "@/components/organisms/Footer";
import { Header } from "@/components/organisms/Header";
import { Providers } from "@/components/templates/Providers";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.scss";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${notoSans.className} antialiased`}
      >
        <Providers>
          <main className="main_layout">
            <Header />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
